*** Settings ***
Library    RemoteSwingLibrary
Resource    ../../../files/keywords.resource
Test Setup       Setup before every tests
Test Teardown    Teardown after every tests

*** Test Cases ***
test_1
    Lock Employee
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF    $ver == '5'    
        ${create_ddl}=    Set Variable    CREATE OR ALTER PROCEDURE DATA_TYPE ( NUM_ENTRIES INTEGER ) AS DECLARE i1 INT; DECLARE i2 INTEGER; DECLARE i3 FLOAT; DECLARE i4 BLOB; DECLARE i5 DOUBLE PRECISION; DECLARE i6 CUSTNO; DECLARE i7 REAL; DECLARE i8 LONG FLOAT; DECLARE i9 BIGINT; DECLARE i10 BOOLEAN; DECLARE i11 BINARY(10); DECLARE i12 CHAR(10) CHARACTER SET OCTETS; DECLARE i13 CHAR(10); DECLARE i14 CHARACTER(10); DECLARE i15 DATE; DECLARE i16 DECIMAL(2,2); DECLARE i17 DEC(2,2); DECLARE i18 DECFLOAT(16); DECLARE i19 INT128; DECLARE i20 NATIONAL CHARACTER(10); DECLARE i21 NATIONAL CHAR(10); DECLARE i22 NCHAR(10); DECLARE i23 NATIONAL CHARACTER VARYING(10); DECLARE i24 NUMERIC(2,2); DECLARE i25 SMALLINT; DECLARE i26 TIME WITHOUT TIME ZONE; DECLARE i27 TIME; DECLARE i28 TIME WITH TIME ZONE; DECLARE i29 TIMESTAMP WITHOUT TIME ZONE; DECLARE i30 TIMESTAMP; DECLARE i31 TIMESTAMP WITH TIME ZONE; DECLARE i32 VARBINARY(10); DECLARE i33 VARCHAR(10) CHARACTER SET OCTETS; DECLARE i34 VARCHAR(10); BEGIN END;
    ELSE IF    $ver == '3'
        ${create_ddl}=    Set Variable    CREATE OR ALTER PROCEDURE DATA_TYPE ( NUM_ENTRIES INTEGER ) AS DECLARE i1 INT; DECLARE i2 INTEGER; DECLARE i3 FLOAT; DECLARE i4 BLOB; DECLARE i5 DOUBLE PRECISION; DECLARE i6 CUSTNO; DECLARE i7 REAL; DECLARE i8 LONG FLOAT; DECLARE i9 BIGINT; DECLARE i10 BOOLEAN; DECLARE i12 CHAR(10) CHARACTER SET OCTETS; DECLARE i13 CHAR(10); DECLARE i14 CHARACTER(10); DECLARE i15 DATE; DECLARE i16 DECIMAL(2,2); DECLARE i17 DEC(2,2); DECLARE i20 NATIONAL CHARACTER(10); DECLARE i21 NATIONAL CHAR(10); DECLARE i22 NCHAR(10); DECLARE i23 NATIONAL CHARACTER VARYING(10); DECLARE i24 NUMERIC(2,2); DECLARE i25 SMALLINT; DECLARE i27 TIME; DECLARE i30 TIMESTAMP; DECLARE i33 VARCHAR(10) CHARACTER SET OCTETS; DECLARE i34 VARCHAR(10); BEGIN END;
    ELSE
        ${create_ddl}=    Set Variable    CREATE OR ALTER PROCEDURE DATA_TYPE AUTHID OWNER ( NUM_ENTRIES INTEGER ) AS DECLARE i1 INT; DECLARE i2 INTEGER; DECLARE i3 FLOAT; DECLARE i4 BLOB; DECLARE i5 DOUBLE PRECISION; DECLARE i6 CUSTNO; DECLARE i7 REAL; DECLARE i8 LONG FLOAT; DECLARE i9 BIGINT; DECLARE i12 CHAR(10) CHARACTER SET OCTETS; DECLARE i13 CHAR(10); DECLARE i14 CHARACTER(10); DECLARE i15 DATE; DECLARE i16 DECIMAL(2,2); DECLARE i17 DEC(2,2); DECLARE i20 NATIONAL CHARACTER(10); DECLARE i21 NATIONAL CHAR(10); DECLARE i22 NCHAR(10); DECLARE i23 NATIONAL CHARACTER VARYING(10); DECLARE i24 NUMERIC(2,2); DECLARE i25 SMALLINT; DECLARE i27 TIME; DECLARE i30 TIMESTAMP; DECLARE i33 VARCHAR(10) CHARACTER SET OCTETS; DECLARE i34 VARCHAR(10); BEGIN END;
    END
    Execute Immediate    ${create_ddl}
    Open connection
    Click On Tree Node   0    New Connection|Procedures (11)|DATA_TYPE   2
    ${ddl}=    Get Text Field Value    1
    Should Be Equal As Strings    ${ddl}    ${create_ddl}    strip_spaces=${True}    collapse_spaces=${True}