*** Settings ***
Library    RemoteSwingLibrary
Library    Process
Library    Collections
Resource    ../../files/keywords.resource
Test Setup       Setup
Test Teardown    Teardown after every tests

*** Test Cases ***
test_1
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF  ${{$ver == '5.0'}}
        action_INCREMENT_FIELDS    SELECT    SELECT DEFAULT_IDENTITY_C, ALWAYS_IDENTITY_C, SEQUENCE_C, SEQUENCE_C_2, COMPUTED_C FROM INCREMENT_FIELDS;
    ELSE
        action_INCREMENT_FIELDS    SELECT    SELECT DEFAULT_IDENTITY_C, SEQUENCE_C, SEQUENCE_C_2, COMPUTED_C FROM INCREMENT_FIELDS;
    END

test_2
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF  ${{$ver == '5.0'}}
        action_INCREMENT_FIELDS    INSERT    INSERT INTO INCREMENT_FIELDS ( DEFAULT_IDENTITY_C, ALWAYS_IDENTITY_C, SEQUENCE_C, SEQUENCE_C_2, COMPUTED_C ) VALUES ( DEFAULT, DEFAULT, :SEQUENCE_C, :SEQUENCE_C_2, DEFAULT );
    ELSE
        action_INCREMENT_FIELDS    INSERT    INSERT INTO INCREMENT_FIELDS ( SEQUENCE_C, SEQUENCE_C_2 ) VALUES ( :SEQUENCE_C, :SEQUENCE_C_2 );
    END
    
test_3
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF  ${{$ver == '5.0'}}
        action_INCREMENT_FIELDS    UPDATE    UPDATE INCREMENT_FIELDS SET DEFAULT_IDENTITY_C = DEFAULT, ALWAYS_IDENTITY_C = DEFAULT, SEQUENCE_C = :SEQUENCE_C, SEQUENCE_C_2 = :SEQUENCE_C_2, COMPUTED_C = DEFAULT;
    ELSE
        action_INCREMENT_FIELDS    UPDATE    UPDATE INCREMENT_FIELDS SET SEQUENCE_C = :SEQUENCE_C, SEQUENCE_C_2 = :SEQUENCE_C_2;
    END

test_4
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF  ${{$ver == '5.0'}}
        action_INCREMENT_FIELDS    CREATE    CREATE TABLE INCREMENT_FIELDS ( DEFAULT_IDENTITY_C BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), ALWAYS_IDENTITY_C BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1), SEQUENCE_C SMALLINT, SEQUENCE_C_2 BIGINT NOT NULL, COMPUTED_C COMPUTED BY (0 + 1));
    ELSE
        action_INCREMENT_FIELDS    CREATE    CREATE TABLE INCREMENT_FIELDS ( DEFAULT_IDENTITY_C BIGINT GENERATED BY DEFAULT AS IDENTITY, SEQUENCE_C SMALLINT, SEQUENCE_C_2 BIGINT NOT NULL, COMPUTED_C COMPUTED BY (0 + 1));
    END


test_5
    action_OTHER_TABLE    SELECT    SELECT INCREMENT_C, COMPUTED_C FROM OTHER_TABLE;

test_6
    action_OTHER_TABLE    INSERT    INSERT INTO OTHER_TABLE DEFAULT VALUES;

test_7
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF  ${{$ver == '5.0'}}
        action_OTHER_TABLE    UPDATE    UPDATE OTHER_TABLE SET INCREMENT_C = DEFAULT, COMPUTED_C = DEFAULT;
    ELSE
        action_OTHER_TABLE    UPDATE    UPDATE OTHER_TABLE SET <field_name> = :<param_name>;
    END

test_8
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    IF  ${{$ver == '5.0'}}
        action_OTHER_TABLE    CREATE    CREATE TABLE OTHER_TABLE ( INCREMENT_C BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1), COMPUTED_C COMPUTED BY (0 + 1));
    ELSE
        action_OTHER_TABLE    CREATE    CREATE TABLE OTHER_TABLE ( INCREMENT_C BIGINT GENERATED BY DEFAULT AS IDENTITY, COMPUTED_C COMPUTED BY (0 + 1));
    END

*** Keywords ***
action_INCREMENT_FIELDS
    [Arguments]    ${type}    ${expected}
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    Lock Employee
    IF  ${{$ver == '5.0'}}
        Execute Immediate    CREATE TABLE INCREMENT_FIELDS (DEFAULT_IDENTITY_C BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ALWAYS_IDENTITY_C BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, SEQUENCE_C SMALLINT, SEQUENCE_C_2 BIGINT NOT NULL, COMPUTED_C COMPUTED BY (0 + 1))
    ELSE
        Execute Immediate    CREATE TABLE INCREMENT_FIELDS (DEFAULT_IDENTITY_C BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, SEQUENCE_C SMALLINT, SEQUENCE_C_2 BIGINT NOT NULL, COMPUTED_C COMPUTED BY (0 + 1))
    END
    Open connection
    Select From Tree Node Popup Menu   0    New Connection|Tables (11)|INCREMENT_FIELDS    Generate SQL|${type} statement
    ${res}=    Get Text Field Value    0
    Should Be Equal As Strings    ${res}     ${expected}    strip_spaces=${True}    collapse_spaces=${True}

action_OTHER_TABLE
    [Arguments]    ${type}    ${expected}
    Lock Employee
    Execute Immediate    CREATE TABLE OTHER_TABLE (INCREMENT_C BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, COMPUTED_C COMPUTED BY (0 + 1))
    Open connection
    Select From Tree Node Popup Menu   0    New Connection|Tables (11)|OTHER_TABLE    Generate SQL|${type} statement
    ${res}=    Get Text Field Value    0
    Should Be Equal As Strings    ${res}     ${expected}    strip_spaces=${True}    collapse_spaces=${True}

Setup
    ${info}=    Get Server Info
    ${ver}=     Set Variable    ${info}[1]
    Skip If    ${{$ver == '2.6'}}
    Setup before every tests